config:
  outputs: |
    [OUTPUT]
        Name es
        Match kube.*
        Host opensearch-cluster-master
        Port 9200
        tls   On
        tls.verify Off
        HTTP_User   admin
        HTTP_Passwd lufIHI11!
        Suppress_Type_Name On
        Logstash_Format On
        Retry_Limit False

    [OUTPUT]
        Name es
        Match host.*
        Host opensearch-cluster-master
        Port 9200
        tls   On
        tls.verify Off
        HTTP_User   admin
        HTTP_Passwd lufIHI11!
        Suppress_Type_Name On
        Logstash_Format On
        Logstash_Prefix node
        Retry_Limit False